### ISSUE TITLE
Key_1 (line 94) store tuple in each loop

### ISSUE THREAD

**Issue by cobvinicius** [lucasrdalcol/PSR_Assignment1_P2_G8#1]

**Comment by cobvinicius** [comment]
- [x] Create a List

**Comment by cobvinicius** [comment]
Create in "parameters":

- [x] type_average_duration 
- [x] type_hit_average_duration
- [x] type_miss_average_duration

**Comment by lucasrdalcol** [comment]
All done in this issue.
