### ISSUE TITLE
Optimize the average calculations

### ISSUE THREAD

**Issue by cobvinicius** [lucasrdalcol/PSR_Assignment1_P2_G8#7]
Index from the complete list with namedtuples. Now we are creating other lists to compute the averages needed.

**Comment by lucasrdalcol** [comment]
Type average duration is optimized. Type hit and miss average duration is still needed.

**Comment by rodrigof1998** [comment]
I do a for cycle to access each element of input_list. After a do a if to compare the received and requested character and if its equal append in the list of type_hit_average_duration, if not append in the type_miss_average_duration. 
Is the most pytonic way? Probably not. But works.

**Comment by rodrigof1998** [comment]
We realize that its not the pythonic way so i use list comprehension to make it work in one line instruction.
