### ISSUE TITLE
Ask to the user if he wants to try again or to quit the program

### ISSUE THREAD

**Issue by lucasrdalcol** [lucasrdalcol/PSR_Assignment1_P2_G8#8]
If the user press 't', he wants to try again, and rerun the test. If he wants to quit the program, he types 'q'.

**Comment by josepedropinto-pt** [comment]
Almost solved this issue, i used os.system to run terminal command in python code. 
Now the user inserts input to run again or quit game and the code runs by default  "./main.py -mv 5". The goal is to run the last line from history command. The command  "!!" runs the last terminal command but it's not working on os.system

**Comment by cobvinicius** [comment]
Issue solved and working well. However, it can be improved with the history command.

**Comment by lucasrdalcol** [comment]
This is done. Closing it.
